"""Initial schema

Revision ID: 0fc81bbb8a29
Revises:
Create Date: 2026-06-28 01:34:26.495689

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '0fc81bbb8a29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
