"""Add assertions to action

Revision ID: 36e571bf8bb4
Revises: 0fc81bbb8a29
Create Date: 2026-06-28 01:46:27.280993

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36e571bf8bb4'
down_revision: Union[str, Sequence[str], None] = '0fc81bbb8a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('assertions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'assertions')
    # ### end Alembic commands ###
